// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: auction/auction/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetAuctionInfoRequest struct {
	AuctionId string `protobuf:"bytes,1,opt,name=auctionId,proto3" json:"auctionId,omitempty"`
}

func (m *QueryGetAuctionInfoRequest) Reset()         { *m = QueryGetAuctionInfoRequest{} }
func (m *QueryGetAuctionInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuctionInfoRequest) ProtoMessage()    {}
func (*QueryGetAuctionInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{2}
}
func (m *QueryGetAuctionInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuctionInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuctionInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuctionInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuctionInfoRequest.Merge(m, src)
}
func (m *QueryGetAuctionInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuctionInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuctionInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuctionInfoRequest proto.InternalMessageInfo

func (m *QueryGetAuctionInfoRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

type QueryGetAuctionInfoResponse struct {
	AuctionInfo AuctionInfo `protobuf:"bytes,1,opt,name=auctionInfo,proto3" json:"auctionInfo"`
}

func (m *QueryGetAuctionInfoResponse) Reset()         { *m = QueryGetAuctionInfoResponse{} }
func (m *QueryGetAuctionInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuctionInfoResponse) ProtoMessage()    {}
func (*QueryGetAuctionInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{3}
}
func (m *QueryGetAuctionInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuctionInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuctionInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuctionInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuctionInfoResponse.Merge(m, src)
}
func (m *QueryGetAuctionInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuctionInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuctionInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuctionInfoResponse proto.InternalMessageInfo

func (m *QueryGetAuctionInfoResponse) GetAuctionInfo() AuctionInfo {
	if m != nil {
		return m.AuctionInfo
	}
	return AuctionInfo{}
}

type QueryAllAuctionInfoRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAuctionInfoRequest) Reset()         { *m = QueryAllAuctionInfoRequest{} }
func (m *QueryAllAuctionInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAuctionInfoRequest) ProtoMessage()    {}
func (*QueryAllAuctionInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{4}
}
func (m *QueryAllAuctionInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuctionInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuctionInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuctionInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuctionInfoRequest.Merge(m, src)
}
func (m *QueryAllAuctionInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuctionInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuctionInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuctionInfoRequest proto.InternalMessageInfo

func (m *QueryAllAuctionInfoRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAuctionInfoResponse struct {
	AuctionInfo []AuctionInfo       `protobuf:"bytes,1,rep,name=auctionInfo,proto3" json:"auctionInfo"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAuctionInfoResponse) Reset()         { *m = QueryAllAuctionInfoResponse{} }
func (m *QueryAllAuctionInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAuctionInfoResponse) ProtoMessage()    {}
func (*QueryAllAuctionInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{5}
}
func (m *QueryAllAuctionInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuctionInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuctionInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuctionInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuctionInfoResponse.Merge(m, src)
}
func (m *QueryAllAuctionInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuctionInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuctionInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuctionInfoResponse proto.InternalMessageInfo

func (m *QueryAllAuctionInfoResponse) GetAuctionInfo() []AuctionInfo {
	if m != nil {
		return m.AuctionInfo
	}
	return nil
}

func (m *QueryAllAuctionInfoResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetActiveAuctionsListRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetActiveAuctionsListRequest) Reset()         { *m = QueryGetActiveAuctionsListRequest{} }
func (m *QueryGetActiveAuctionsListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetActiveAuctionsListRequest) ProtoMessage()    {}
func (*QueryGetActiveAuctionsListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{6}
}
func (m *QueryGetActiveAuctionsListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetActiveAuctionsListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetActiveAuctionsListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetActiveAuctionsListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetActiveAuctionsListRequest.Merge(m, src)
}
func (m *QueryGetActiveAuctionsListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetActiveAuctionsListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetActiveAuctionsListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetActiveAuctionsListRequest proto.InternalMessageInfo

func (m *QueryGetActiveAuctionsListRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetActiveAuctionsListResponse struct {
	ActiveAuctionsList ActiveAuctionsList `protobuf:"bytes,1,opt,name=ActiveAuctionsList,proto3" json:"ActiveAuctionsList"`
}

func (m *QueryGetActiveAuctionsListResponse) Reset()         { *m = QueryGetActiveAuctionsListResponse{} }
func (m *QueryGetActiveAuctionsListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetActiveAuctionsListResponse) ProtoMessage()    {}
func (*QueryGetActiveAuctionsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{7}
}
func (m *QueryGetActiveAuctionsListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetActiveAuctionsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetActiveAuctionsListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetActiveAuctionsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetActiveAuctionsListResponse.Merge(m, src)
}
func (m *QueryGetActiveAuctionsListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetActiveAuctionsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetActiveAuctionsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetActiveAuctionsListResponse proto.InternalMessageInfo

func (m *QueryGetActiveAuctionsListResponse) GetActiveAuctionsList() ActiveAuctionsList {
	if m != nil {
		return m.ActiveAuctionsList
	}
	return ActiveAuctionsList{}
}

type QueryAllActiveAuctionsListRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllActiveAuctionsListRequest) Reset()         { *m = QueryAllActiveAuctionsListRequest{} }
func (m *QueryAllActiveAuctionsListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllActiveAuctionsListRequest) ProtoMessage()    {}
func (*QueryAllActiveAuctionsListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{8}
}
func (m *QueryAllActiveAuctionsListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllActiveAuctionsListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllActiveAuctionsListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllActiveAuctionsListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllActiveAuctionsListRequest.Merge(m, src)
}
func (m *QueryAllActiveAuctionsListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllActiveAuctionsListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllActiveAuctionsListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllActiveAuctionsListRequest proto.InternalMessageInfo

func (m *QueryAllActiveAuctionsListRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllActiveAuctionsListResponse struct {
	ActiveAuctionsList []ActiveAuctionsList `protobuf:"bytes,1,rep,name=ActiveAuctionsList,proto3" json:"ActiveAuctionsList"`
	Pagination         *query.PageResponse  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllActiveAuctionsListResponse) Reset()         { *m = QueryAllActiveAuctionsListResponse{} }
func (m *QueryAllActiveAuctionsListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllActiveAuctionsListResponse) ProtoMessage()    {}
func (*QueryAllActiveAuctionsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b00c0271385f7fe, []int{9}
}
func (m *QueryAllActiveAuctionsListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllActiveAuctionsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllActiveAuctionsListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllActiveAuctionsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllActiveAuctionsListResponse.Merge(m, src)
}
func (m *QueryAllActiveAuctionsListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllActiveAuctionsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllActiveAuctionsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllActiveAuctionsListResponse proto.InternalMessageInfo

func (m *QueryAllActiveAuctionsListResponse) GetActiveAuctionsList() []ActiveAuctionsList {
	if m != nil {
		return m.ActiveAuctionsList
	}
	return nil
}

func (m *QueryAllActiveAuctionsListResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "auction.auction.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "auction.auction.QueryParamsResponse")
	proto.RegisterType((*QueryGetAuctionInfoRequest)(nil), "auction.auction.QueryGetAuctionInfoRequest")
	proto.RegisterType((*QueryGetAuctionInfoResponse)(nil), "auction.auction.QueryGetAuctionInfoResponse")
	proto.RegisterType((*QueryAllAuctionInfoRequest)(nil), "auction.auction.QueryAllAuctionInfoRequest")
	proto.RegisterType((*QueryAllAuctionInfoResponse)(nil), "auction.auction.QueryAllAuctionInfoResponse")
	proto.RegisterType((*QueryGetActiveAuctionsListRequest)(nil), "auction.auction.QueryGetActiveAuctionsListRequest")
	proto.RegisterType((*QueryGetActiveAuctionsListResponse)(nil), "auction.auction.QueryGetActiveAuctionsListResponse")
	proto.RegisterType((*QueryAllActiveAuctionsListRequest)(nil), "auction.auction.QueryAllActiveAuctionsListRequest")
	proto.RegisterType((*QueryAllActiveAuctionsListResponse)(nil), "auction.auction.QueryAllActiveAuctionsListResponse")
}

func init() { proto.RegisterFile("auction/auction/query.proto", fileDescriptor_2b00c0271385f7fe) }

var fileDescriptor_2b00c0271385f7fe = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4d, 0x6b, 0x13, 0x41,
	0x18, 0xc7, 0xb3, 0x69, 0x0d, 0x74, 0x0a, 0x15, 0xc6, 0x4a, 0x74, 0x1b, 0x37, 0x3a, 0x5a, 0xab,
	0x69, 0xdd, 0x21, 0x09, 0x5e, 0xbc, 0xa5, 0x88, 0xa5, 0xd0, 0x43, 0xcd, 0x4d, 0x2f, 0x61, 0x93,
	0x6c, 0x97, 0xc5, 0xed, 0xce, 0x36, 0x33, 0x29, 0x96, 0x52, 0x04, 0x3f, 0x81, 0x28, 0x78, 0xf1,
	0x2b, 0x08, 0xe2, 0xb7, 0xc8, 0xb1, 0xe0, 0xc5, 0x93, 0x48, 0xe2, 0x07, 0x91, 0x9d, 0x79, 0x36,
	0x6f, 0xbb, 0x9b, 0xa6, 0xda, 0xd3, 0x24, 0x33, 0xcf, 0xcb, 0xef, 0xff, 0x3c, 0x33, 0xcf, 0xa2,
	0x35, 0xab, 0xdb, 0x12, 0x2e, 0xf3, 0x69, 0xb4, 0x1e, 0x75, 0xed, 0xce, 0x89, 0x19, 0x74, 0x98,
	0x60, 0xf8, 0x3a, 0x6c, 0x9a, 0xb0, 0xea, 0xab, 0x0e, 0x73, 0x98, 0x3c, 0xa3, 0xe1, 0x2f, 0x65,
	0xa6, 0x17, 0x1c, 0xc6, 0x1c, 0xcf, 0xa6, 0x56, 0xe0, 0x52, 0xcb, 0xf7, 0x99, 0xb0, 0x42, 0x63,
	0x0e, 0xa7, 0xa5, 0x16, 0xe3, 0x87, 0x8c, 0xd3, 0xa6, 0xc5, 0x6d, 0x15, 0x9d, 0x1e, 0x97, 0x9b,
	0xb6, 0xb0, 0xca, 0x34, 0xb0, 0x1c, 0xd7, 0x97, 0xc6, 0x51, 0xa4, 0x69, 0x9a, 0xc0, 0xea, 0x58,
	0x87, 0x51, 0x24, 0x32, 0x7d, 0x0a, 0x6b, 0xc3, 0xf5, 0x0f, 0x22, 0x96, 0x52, 0xcc, 0xa6, 0x25,
	0xdc, 0x63, 0xbb, 0x01, 0x7f, 0x79, 0xc3, 0x73, 0xb9, 0x50, 0xb6, 0x64, 0x15, 0xe1, 0x97, 0x21,
	0xcf, 0xbe, 0x4c, 0x52, 0xb7, 0x8f, 0xba, 0x36, 0x17, 0x64, 0x0f, 0xdd, 0x98, 0xd8, 0xe5, 0x01,
	0xf3, 0xb9, 0x8d, 0x9f, 0xa2, 0x9c, 0x82, 0xb9, 0xa5, 0xdd, 0xd5, 0x1e, 0x2d, 0x57, 0xf2, 0xe6,
	0x54, 0x71, 0x4c, 0xe5, 0xb0, 0xbd, 0xd8, 0xfb, 0x55, 0xcc, 0xd4, 0xc1, 0x98, 0x3c, 0x43, 0xba,
	0x8c, 0xb6, 0x63, 0x8b, 0x9a, 0xb2, 0xdb, 0xf5, 0x0f, 0x18, 0xe4, 0xc2, 0x05, 0xb4, 0x04, 0xde,
	0xbb, 0x6d, 0x19, 0x77, 0xa9, 0x3e, 0xda, 0x20, 0x2d, 0xb4, 0x96, 0xe8, 0x0b, 0x44, 0xcf, 0xd1,
	0xb2, 0x35, 0xda, 0x06, 0xac, 0x42, 0x0c, 0x6b, 0xcc, 0x15, 0xd8, 0xc6, 0xdd, 0x48, 0x1b, 0x00,
	0x6b, 0x9e, 0x97, 0x00, 0xf8, 0x02, 0xa1, 0x51, 0x93, 0x20, 0xc5, 0x43, 0x53, 0x75, 0xd4, 0x0c,
	0x3b, 0x6a, 0xaa, 0xfb, 0x02, 0x1d, 0x35, 0xf7, 0x2d, 0xc7, 0x06, 0xdf, 0xfa, 0x98, 0x27, 0xf9,
	0xaa, 0x81, 0x96, 0xe9, 0x34, 0x69, 0x5a, 0x16, 0xfe, 0x41, 0x0b, 0xde, 0x99, 0xa0, 0xcd, 0x4a,
	0xda, 0x8d, 0x0b, 0x69, 0x15, 0xc2, 0x04, 0x6e, 0x15, 0xdd, 0x1b, 0x56, 0x5e, 0xde, 0x1f, 0x48,
	0xcc, 0xf7, 0x5c, 0x2e, 0xa2, 0xda, 0xac, 0xa0, 0xac, 0xab, 0xba, 0xb6, 0x58, 0xcf, 0xba, 0x6d,
	0xf2, 0x0e, 0x91, 0x59, 0x4e, 0xa0, 0xf4, 0x15, 0xc2, 0xf1, 0x53, 0xa8, 0xec, 0xfd, 0xb8, 0xe0,
	0x98, 0x29, 0xe8, 0x4e, 0x08, 0x42, 0xde, 0x00, 0x75, 0x58, 0xe3, 0x54, 0xea, 0xab, 0xea, 0x68,
	0x4f, 0x03, 0xb9, 0x29, 0xd9, 0x2e, 0x90, 0xbb, 0xf0, 0xdf, 0x72, 0xaf, 0xac, 0xdb, 0x95, 0xcf,
	0x39, 0x74, 0x4d, 0x4a, 0xc1, 0x02, 0xe5, 0xd4, 0x2b, 0xc6, 0x71, 0xb6, 0xf8, 0xa8, 0xd0, 0x1f,
	0xcc, 0x36, 0x52, 0xa9, 0x48, 0xf1, 0xfd, 0x8f, 0x3f, 0x9f, 0xb2, 0xb7, 0x71, 0x9e, 0x26, 0x4f,
	0x37, 0xfc, 0x45, 0x43, 0xcb, 0x63, 0x37, 0x1b, 0x6f, 0x26, 0x87, 0x4d, 0x1c, 0x21, 0xfa, 0xd6,
	0x7c, 0xc6, 0xc0, 0x52, 0x96, 0x2c, 0x9b, 0xf8, 0x31, 0x9d, 0x35, 0x4b, 0xe9, 0xe9, 0x70, 0x08,
	0x9d, 0xe1, 0x8f, 0x1a, 0x5a, 0x19, 0x0b, 0x55, 0xf3, 0xbc, 0x34, 0xc0, 0xc4, 0x11, 0x92, 0x06,
	0x98, 0x3c, 0x08, 0xc8, 0xba, 0x04, 0x2c, 0xe2, 0x3b, 0x33, 0x01, 0xf1, 0x77, 0x2d, 0xe9, 0x5e,
	0xe1, 0x4a, 0x7a, 0x31, 0xd2, 0x1e, 0x84, 0x5e, 0xbd, 0x94, 0x0f, 0x60, 0x56, 0x24, 0xe6, 0x16,
	0x2e, 0xd1, 0x79, 0xbe, 0x37, 0xf4, 0xd4, 0x6d, 0x9f, 0xe1, 0x6f, 0x1a, 0xba, 0x19, 0x0f, 0x19,
	0xd6, 0xb3, 0x92, 0x5e, 0xa2, 0xcb, 0x62, 0xcf, 0x7c, 0x8d, 0xe4, 0x89, 0xc4, 0xde, 0xc0, 0xeb,
	0x73, 0x61, 0x6f, 0x97, 0x7b, 0x7d, 0x43, 0x3b, 0xef, 0x1b, 0xda, 0xef, 0xbe, 0xa1, 0x7d, 0x18,
	0x18, 0x99, 0xf3, 0x81, 0x91, 0xf9, 0x39, 0x30, 0x32, 0xaf, 0xf3, 0x91, 0xdf, 0xdb, 0x61, 0x04,
	0x71, 0x12, 0xd8, 0xbc, 0x99, 0x93, 0x9f, 0xd6, 0xea, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93,
	0x51, 0x6e, 0x28, 0x58, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of AuctionInfo items.
	AuctionInfo(ctx context.Context, in *QueryGetAuctionInfoRequest, opts ...grpc.CallOption) (*QueryGetAuctionInfoResponse, error)
	AuctionInfoAll(ctx context.Context, in *QueryAllAuctionInfoRequest, opts ...grpc.CallOption) (*QueryAllAuctionInfoResponse, error)
	// Queries a list of ActiveAuctionsList items.
	ActiveAuctionsList(ctx context.Context, in *QueryGetActiveAuctionsListRequest, opts ...grpc.CallOption) (*QueryGetActiveAuctionsListResponse, error)
	ActiveAuctionsListAll(ctx context.Context, in *QueryAllActiveAuctionsListRequest, opts ...grpc.CallOption) (*QueryAllActiveAuctionsListResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/auction.auction.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuctionInfo(ctx context.Context, in *QueryGetAuctionInfoRequest, opts ...grpc.CallOption) (*QueryGetAuctionInfoResponse, error) {
	out := new(QueryGetAuctionInfoResponse)
	err := c.cc.Invoke(ctx, "/auction.auction.Query/AuctionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuctionInfoAll(ctx context.Context, in *QueryAllAuctionInfoRequest, opts ...grpc.CallOption) (*QueryAllAuctionInfoResponse, error) {
	out := new(QueryAllAuctionInfoResponse)
	err := c.cc.Invoke(ctx, "/auction.auction.Query/AuctionInfoAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActiveAuctionsList(ctx context.Context, in *QueryGetActiveAuctionsListRequest, opts ...grpc.CallOption) (*QueryGetActiveAuctionsListResponse, error) {
	out := new(QueryGetActiveAuctionsListResponse)
	err := c.cc.Invoke(ctx, "/auction.auction.Query/ActiveAuctionsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActiveAuctionsListAll(ctx context.Context, in *QueryAllActiveAuctionsListRequest, opts ...grpc.CallOption) (*QueryAllActiveAuctionsListResponse, error) {
	out := new(QueryAllActiveAuctionsListResponse)
	err := c.cc.Invoke(ctx, "/auction.auction.Query/ActiveAuctionsListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of AuctionInfo items.
	AuctionInfo(context.Context, *QueryGetAuctionInfoRequest) (*QueryGetAuctionInfoResponse, error)
	AuctionInfoAll(context.Context, *QueryAllAuctionInfoRequest) (*QueryAllAuctionInfoResponse, error)
	// Queries a list of ActiveAuctionsList items.
	ActiveAuctionsList(context.Context, *QueryGetActiveAuctionsListRequest) (*QueryGetActiveAuctionsListResponse, error)
	ActiveAuctionsListAll(context.Context, *QueryAllActiveAuctionsListRequest) (*QueryAllActiveAuctionsListResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AuctionInfo(ctx context.Context, req *QueryGetAuctionInfoRequest) (*QueryGetAuctionInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionInfo not implemented")
}
func (*UnimplementedQueryServer) AuctionInfoAll(ctx context.Context, req *QueryAllAuctionInfoRequest) (*QueryAllAuctionInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionInfoAll not implemented")
}
func (*UnimplementedQueryServer) ActiveAuctionsList(ctx context.Context, req *QueryGetActiveAuctionsListRequest) (*QueryGetActiveAuctionsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveAuctionsList not implemented")
}
func (*UnimplementedQueryServer) ActiveAuctionsListAll(ctx context.Context, req *QueryAllActiveAuctionsListRequest) (*QueryAllActiveAuctionsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveAuctionsListAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.auction.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuctionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAuctionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuctionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.auction.Query/AuctionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuctionInfo(ctx, req.(*QueryGetAuctionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuctionInfoAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAuctionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuctionInfoAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.auction.Query/AuctionInfoAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuctionInfoAll(ctx, req.(*QueryAllAuctionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActiveAuctionsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetActiveAuctionsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActiveAuctionsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.auction.Query/ActiveAuctionsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActiveAuctionsList(ctx, req.(*QueryGetActiveAuctionsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActiveAuctionsListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllActiveAuctionsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActiveAuctionsListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auction.auction.Query/ActiveAuctionsListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActiveAuctionsListAll(ctx, req.(*QueryAllActiveAuctionsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auction.auction.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AuctionInfo",
			Handler:    _Query_AuctionInfo_Handler,
		},
		{
			MethodName: "AuctionInfoAll",
			Handler:    _Query_AuctionInfoAll_Handler,
		},
		{
			MethodName: "ActiveAuctionsList",
			Handler:    _Query_ActiveAuctionsList_Handler,
		},
		{
			MethodName: "ActiveAuctionsListAll",
			Handler:    _Query_ActiveAuctionsListAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auction/auction/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetAuctionInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuctionInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuctionInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AuctionId) > 0 {
		i -= len(m.AuctionId)
		copy(dAtA[i:], m.AuctionId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AuctionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAuctionInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuctionInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuctionInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AuctionInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAuctionInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuctionInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuctionInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAuctionInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuctionInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuctionInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuctionInfo) > 0 {
		for iNdEx := len(m.AuctionInfo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuctionInfo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetActiveAuctionsListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetActiveAuctionsListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetActiveAuctionsListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetActiveAuctionsListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetActiveAuctionsListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetActiveAuctionsListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ActiveAuctionsList.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllActiveAuctionsListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllActiveAuctionsListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllActiveAuctionsListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllActiveAuctionsListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllActiveAuctionsListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllActiveAuctionsListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ActiveAuctionsList) > 0 {
		for iNdEx := len(m.ActiveAuctionsList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActiveAuctionsList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetAuctionInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuctionId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAuctionInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AuctionInfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAuctionInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAuctionInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuctionInfo) > 0 {
		for _, e := range m.AuctionInfo {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetActiveAuctionsListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetActiveAuctionsListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ActiveAuctionsList.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllActiveAuctionsListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllActiveAuctionsListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ActiveAuctionsList) > 0 {
		for _, e := range m.ActiveAuctionsList {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuctionInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuctionInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuctionInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuctionInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuctionInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuctionInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AuctionInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuctionInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuctionInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuctionInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuctionInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuctionInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuctionInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionInfo = append(m.AuctionInfo, AuctionInfo{})
			if err := m.AuctionInfo[len(m.AuctionInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetActiveAuctionsListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetActiveAuctionsListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetActiveAuctionsListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetActiveAuctionsListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetActiveAuctionsListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetActiveAuctionsListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveAuctionsList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActiveAuctionsList.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllActiveAuctionsListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllActiveAuctionsListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllActiveAuctionsListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllActiveAuctionsListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllActiveAuctionsListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllActiveAuctionsListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveAuctionsList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActiveAuctionsList = append(m.ActiveAuctionsList, ActiveAuctionsList{})
			if err := m.ActiveAuctionsList[len(m.ActiveAuctionsList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
